### ISSUE TITLE
Minor - suggested change to Battery message in Recently 

### ISSUE THREAD

**Issue by alecm** [bspranger/Xiaomi#104]
I think that for consistency we should change 'recently' message for battery reporting from 

descriptionText : "${device.displayName} is at ${roundedPct}% (${rawVolts} Volts)"

to

descriptionText : "${device.displayName} Battery at ${roundedPct}% (${rawVolts} Volts)"

since:
- we always indicate the variable on all the other recently messages
- there's another field w/ percent (e.g., humidity) - I know volts would seem to rule that out but it's still a bit confusing if you see my first example below
- battery icon doesn't show on iOS recently (which is why we put in the volts) 

that would change it from 

![image](https://user-images.githubusercontent.com/3035095/36643519-5b680e74-1a1a-11e8-97a7-310af0d50927.png)

to 

![image](https://user-images.githubusercontent.com/3035095/36643539-bc218bf0-1a1a-11e8-910c-681a880452b4.png)

on iOS (don't have Android to test - not quite as relevant since apparently the icon does show there - but even so there should be consistency) 

Thoughts? 

Alec

**Comment by alecm** [comment]
Note I've created a pull for this once people have had a chance to review.   @fozz333 I didn't make change for the smoke detector because it looks like it's battery message is a previous version - and I didn't want to mess with your "baby" :-).  That said, would be happy to add it to the pull if you want me to and people here agree.

**Comment by bspranger** [comment]
I like it, proceed!

**Comment by veeceeoh** [comment]
Same here - and as I mentioned in my comment on the pull, you should go ahead an apply the change to the smoke sensor DTH as well, since it's using the new icon too.

**Comment by alecm** [comment]
Ok - was able to update successfuly from repo - no erroring - assume that means they all compile fine - though I checked the first five just to be extra sure.    Closing.
