### ISSUE TITLE
Enhancement Suggestion: Info / Debug message display preference settings

### ISSUE THREAD

**Issue by veeceeoh** [bspranger/Xiaomi#112]
Inspired by Hubitat's native device drivers, I'd like to suggest adding preference setting toggles for `info` and/or `debug` log message display.

I have already built code for this in my updated round "Original" Xiaomi button DTH currently being beta tested (Pull Request #110). Here are what they look like in the device preferences page:

![img_2336](https://user-images.githubusercontent.com/33558908/37793943-4af6d630-2dcd-11e8-89c6-c2e22fda1320.PNG)

I set up the defaults at pairing for only info log messages to be displayed, and when the debug log toggle is also set, it's easy to see which kinds of messages are being displayed:

<img width="1129" alt="screen shot 2018-03-22 at 12 18 46 pm" src="https://user-images.githubusercontent.com/33558908/37793857-0f64b588-2dcd-11e8-895e-7a1799e03a5d.png">

If people think this would be a welcome enhancement, then I could do a Pull Request on all the other DTHs so people can try it out.

**Comment by alecm** [comment]
As an advanced user, I really like it! - trying to speak for the newbie/end user - this could be confusing as heck - maybe we could look at a basic versus advanced mode for users? The DTHs already work so well, I have a hard time with adding more complexity to confuse the new user, just because they're cool.  (speaking from my Product Manager days)

**Comment by veeceeoh** [comment]
No problem - it's all a matter of the way you "spin" it:
* Info log messages = Useful for basic users
* Debug log messages = Useful for advanced users / troubleshooting

As the DTHs stand right now, I think having all those debug messages are already confusing for most users, and they just add a lot of "noise" to the Live Logging page.

With the default of Info log messages, the messages that will be output are very straightforward and easy to understand by anyone.

**Comment by alecm** [comment]
How about a toggle that turns on or off advanced settings such as battery voltage, test motion override, logging, etc. ?  And, I don't think most users are going into the logs -

**Comment by veeceeoh** [comment]
I'm not sure I understand. This suggestion is just related to being able to turn on / off the log output.

Also, with SmartThings device handlers there is no way I am aware of to toggle the view of or "hide" certain settings. That's only available in Apps.

But yes, I agree that nobody _has_ to look at the logs; any information there is just helpful in confirming that a device is working the way it's supposed to.

**Comment by alecm** [comment]
ah, you're right about DTH versus Apps - maybe then just set the advanced options below the "only adjust these if you know what you're doing" text for the voltage - I just think that a lot of toggles/ settings can be confusing for the early user who just wants to set it and move on

**Comment by veeceeoh** [comment]
Sure, I have updated the round Button beta DTH to put them under an "Advanced Settings" heading, and I could do the same for the new Motion Sensor DTH Testing Mode toggle (with it's long explanation).

But I do think leaving the default of "on" for display of the info log messages would help users of any level. Here's some examples of what that would look like:

**When device is paired**
```
[info] Xiaomi Button: Set health checkInterval when configured
[info] Xiaomi Button: Configuring
[info] Xiaomi Button: Setting Battery Changed to current date for newly paired device 
[info] Xiaomi Button: Installing
```

**During Use**
```
[info] Xiaomi Button: Battery at 100% (3.025 Volts)
[info] Xiaomi Button: Virtual App Button Pressed
[info] Xiaomi Button: Button was held
[info] Xiaomi Button: Button was pushed
```

**Change a preference setting and save**
```
[info] Xiaomi Button: Info message logging enabled
[info] Xiaomi Button: Set health checkInterval when preferences updated
[info] Xiaomi Button: Updating preference settings
[info] Xiaomi Button: Info message logging enabled
[info] Xiaomi Button: Set health checkInterval when preferences updated
[info] Xiaomi Button: Updating preference settings
```
_(Note: The double run of `update()` is a SmartThings bug)_

**Motion Sensor Example**
```
[info] Aqara Motion Sensor: Testing Mode has been deactivated
[info] Aqara Motion Sensor: Reset to no motion (inactive)
[info] Aqara Motion Sensor: Detected motion
[info] Aqara Motion Sensor: Reset to no motion (inactive)
[info] Aqara Motion Sensor: Detected motion
[info] Aqara Motion Sensor: Battery at 95% (2.895 Volts)
[info] Aqara Motion Sensor: Testing Mode activated for 60 minutes
[info] Aqara Motion Sensor: Info message logging enabled
[info] Aqara Motion Sensor: Set health checkInterval when preferences updated
[info] Aqara Motion Sensor: Updating preference settings
[info] Aqara Motion Sensor: Testing Mode activated for 60 minutes
[info] Aqara Motion Sensor: Info message logging enabled
[info] Aqara Motion Sensor: Set health checkInterval when preferences updated
[info] Aqara Motion Sensor: Updating preference settings
[info] Aqara Motion Sensor: Reset to no motion (inactive) after 61 seconds
[info] Aqara Motion Sensor: Detected motion
```
