### ISSUE TITLE
Xiaomi Aqara Temperature Humidity Sensor - Humidity offset not working

### ISSUE THREAD

**Issue by vidarga** [bspranger/Xiaomi#117]
Hi, 
The humidityOffset is not working in the device handler "Xiaomi Aqara Temperature Humidity Sensor"

The problem is that the offset variable "humidityOffset" is not referred to in the device handler is not linked to the value that you entered in the preference input.   I did a quick test replacing the  humidityOffset variable in the Parse function with the humidOffset variable from the preference input  and the humidity value was corrected. 

input "_**humidOffset**_", "number", title:"Humidity Offset", description:"Adjust humidity by this many percent", range: "*..*"

else if (map.name == "humidity") {
  if   (_**humidityOffset**_) {
        map.value = (int)   map.value   + (int) humidityOffset
   }

This code in the Parse function will solve the problem: 

	} else if (map.name == "humidity") {
    	def humidityOffset = humidOffset ? humidOffset : 0
		if (humidityOffset) {
			map.value = (int) map.value + (int) humidityOffset
		}
		updateMinMaxHumidity(map.value)

**Comment by veeceeoh** [comment]
The incorrect code for applying the Humidity Offset setting has been fixed, both in the Aqara and "original" Xiaomi Temp/Humidity Sensor DTHs.

Thank you for identifying the issue!!
