### ISSUE TITLE
Xiaomi Aqara wall single switch 

### ISSUE THREAD

**Issue by Hagshur** [bspranger/Xiaomi#118]
Can’t get it work tryout any DH in here 
Attached picture of my switch type ![Image](https://i.imgur.com/TFXvka0.jpg)

**Comment by veeceeoh** [comment]
I'm sorry, but in order for anyone to make a custom DH for a Xiaomi device, it's best if they own one themselves so they can do testing.

Nobody contributing custom Xiaomi device handlers to this collection owns one of the model switch you have, so that's why there's no DH available.

**Comment by johndoyle** [comment]
I think I have that device and my DH works fine: 
      https://github.com/johndoyle/SmartThingsPersonal/blob/master/devicetypes/Xiaomi/xiaomi-mains-single-switch-no-neutral.groovy
    
Hope this helps
