### ISSUE TITLE
Temp sensor showing as unavailable

### ISSUE THREAD

**Issue by silverman10** [bspranger/Xiaomi#122]
Temp sensor status shows as unavailable, but the temp, humidity and battery are all displayed correctly. 

Using the Aqara Temperature sensor. Its been working okay for a long time, this behaviour started only recently.

`782fecac-2d5d-4196-ba8c-a574e450541e  11:01:40 AM: debug Temperature Sensor: Parse returned [name:battery, value:100, unit:%, isStateChange:true, descriptionText:Temperature Sensor Battery at 100% (3.025 Volts)]
782fecac-2d5d-4196-ba8c-a574e450541e  11:01:40 AM: debug SmartShield(clusterId: 0x0000, command: 0x0a, data: [0x01, 0xff, 0x42, 0x25, 0x01, 0x21, 0xd1, 0x0b, 0x04, 0x21, 0xa8, 0x43, 0x05, 0x21, 0x05, 0x00, 0x06, 0x24, 0x01, 0x00, 0x00, 0x00, 0x00, 0x64, 0x29, 0xf4, 0x07, 0x65, 0x21, 0x34, 0x1d, 0x66, 0x2b, 0x39, 0x88, 0x01, 0x00, 0x0a, 0x21, 0x00, 0x00], destinationEndpoint: 0x01, direction: 0x01, isClusterSpecific: false, isManufacturerSpecific: false, manufacturerId: 0x0000, messageType: 0x00, number: null, options: 0x0100, profileId: 0x0104, senderShortId: 0x7ded, sourceEndpoint: 0x01, text: null)
782fecac-2d5d-4196-ba8c-a574e450541e  11:01:40 AM: debug Temperature Sensor: Parsing description: catchall: 0104 0000 01 01 0100 00 7DED 00 00 0000 0A 01 01FF42250121D10B0421A84305210500062401000000006429F4076521341D662B398801000A210000`

**Comment by veeceeoh** [comment]
This would not be an issue with the device handler code, but rather with SmartThings. Have you tried posting on a Xiaomi device thread on the SmartThings forums?

**Comment by silverman10** [comment]
@veeceeoh thanks. This fixed itself. I checked this morning and see it online. Not sure whats changed.
