### ISSUE TITLE
Xiaomi Aqara Temperature Doesnt Show Connected in Smartthings App (not classic)

### ISSUE THREAD

**Issue by kiwiot** [bspranger/Xiaomi#128]
Smarthub V3 (US edition)
2 x Xiaomi Aqara Temperature Humidity Sensors
Androind Smartthings App latest version

Right so on to the issue. I added the correct device handler and after a night of mucking around got the 2 sensors finally installed by forcing the hub to look for a different sensor - no probs there and the data being reported back to the hub is correctly.

However, when it comes to clicking on the device in the app all I get is “Cannot connect to device. Check device and try again.”

I know from watching logs that the sensors are working like a charm in terms of reporting and according the IDE are connected to the hub, hwoever the one difference I have seen is that “Execution Location” is set to cloud. Dont know if that matters.

Thanks in advance.
Jared

**Comment by veeceeoh** [comment]
Devices with custom device handlers (including those for _all_ Xiaomi/Aqara devices) are currently not officially supported in the new SmartThings mobile App. There are lines of code that need to be added to get devices to be properly recognized, but Samsung have not yet published a reference guide for that.

For now, only the SmartThings "Classic" mobile App will work correctly in recognizing devices with custom device handlers.

Also note: currently the execution location for custom device handler code is always cloud-based. Samsung provides local code execution for _some_ officially supported devices, a larger number supported on the v2/v3 hubs and smaller number on other types of SmartThings hubs.

**Comment by DrZesty** [comment]
Hey Guys. I would like to learn how to modify the Xiaomi Aqara Temperature Humidity Sensor 1.3 code so that like open and close sensors, that when a temp goes above and below a temp, or a Humidity drops below a certain level I can setup a routine.

For some reason I can do this with the aqara Open Close window sensors in Alex Routines, but cant see the humidity temp controls in Alexa.

Any ideas, on what additional code I could add to 1.3 that would enable me to control a device in alexa based upon a change.

Thanks Z
--

**Comment by veeceeoh** [comment]
@DrZesty 

I would recommend using a SmartApp that based on on temp/humidity changes, can trigger a Virtual Switch device which in turn changes the state of a Virtual Contact Sensor that can be added to your Alexa's device list.

Fortunately, SmartThings already provides some of the pieces of the puzzle:

* Virtual Thermostat - Allows a user to to turn on/off a switch based on specific temperature 
* Smart Humidifier - Allows a user to turn on/off a switch based on specific humidity percentage

So all you need to find is a community SmartApp which changes the state of a Virtual Contact Sensor to open/close when a switch device changes to on/off.
