### ISSUE TITLE
Aquara Motion sensors strange behavior

### ISSUE THREAD

**Issue by veonua** [bspranger/Xiaomi#131]
I bought two Motion sensors connect them to SmartThings using handler.
First one works ok, (however it seems it reports more frequent than 60 seconds)

Second one reports only illuminance but not motion event as soon as it connected. After couple of minutes of illuminance it stops to send events at all. it reports only when I click the button.

What are the chances that second sensor is not configured properly? I have not connected one of them (do not remember which) to the Xiaomi hub. Does Hub send configuration on first connect?

**Comment by veonua** [comment]
do you need a log with the current app(master)? I found several alternative
apps that tried to push "refresh" signal to the device. they do produce
some unknown response

**Comment by veeceeoh** [comment]
I'm not sure what you mean.

The log entries I would be looking for can be found by logging into your SmartThings hub's Groovy IDE web-based interface, here:

https://graph.api.smartthings.com

Then select the Live Logging link at the top menu bar. 

<img width="1241" alt="screen shot 2018-12-05 at 10 06 27 am" src="https://user-images.githubusercontent.com/33558908/49534069-7bff6f80-f875-11e8-9afb-fac9b22fae69.png">

Once you have that page open, then create movement in front of your motion sensor. You should see log entries appear. If you could copy the text of those log entries and paste them in a post here that would be very helpful.

**Comment by veonua** [comment]
not much


> e5899f9c-59e6-4c14-b661-638e2f8ab7de  7:19:20 PM: debug Strange sensor parsing: read attr - raw: F0700100007e050042166C756D692E73656E736F725F6D6F74696F6E2E61713201FF42210121BD0B0328150421A83105212D00062400000000000A2100006410000B210800, dni: F070, endpoint: 01, cluster: 0000, size: 7e, attrId: 0005, encoding: 42, value: 6C756D692E73656E736F725F6D6F74696F6E2E61713201FF42210121BD0B0328150421A83105212D00062400000000000A2100006410000B210800

**Comment by veeceeoh** [comment]
I believe that is the check-in message sent by the sensor when the reset button is short-pressed.

In the `value:` portion of that log entry, the hex string `6C756D692E73656E736F725F6D6F74696F6E2E617132` equates to the text string `lumi.sensor_motion.aq2`. That tells me the device is an Aqara Motion Sensor, model RTCGQ11LM.

Is the reset button stuck? Did you press it when this log message appeared?

Keep in mind it is totally possible that you may have received a defective unit.

**Comment by veonua** [comment]
> Is the reset button stuck? 
unlikely
>Did you press it when this log message appeared?
yes

> Keep in mind it is totally possible that you may have received a defective unit.
yes, it's possible. but for coincidence it happened with the unit I did not test with original Hub. And wondering maybe I missed something. The unit still sends heart-beat and apparently able to report luminance data.

**Comment by veeceeoh** [comment]
The way the Aqara Motion Sensor works is that an illuminance report message is sent only when motion is detected. So in the log output you should see an illuminance report message followed by the motion detected message. Did you see any log output for an illuminance report?

**Comment by veonua** [comment]
as I told previously I get illuminance data quite often first 5 minutes after pairing, then it stops and sends only heart-beats.

**Comment by veeceeoh** [comment]
So you do not see any log output in the Live Logging window for the illuminance data reports?

When using [this Aqara Motion Sensor DTH](https://github.com/bspranger/Xiaomi/blob/master/devicetypes/bspranger/xiaomi-aqara-motion-sensor.src/xiaomi-aqara-motion-sensor.groovy), then there must be a debug `parsing: ` message in the Live Logging window for every message received from the sensor.

For motion detected messages, you should see a log message which contains: `cluster: 0406`.

If there are only illuminance report log messages, then I can only guess the unit is defective because I don't have any other information to know what is happening.

I'm sorry that I cannot help any more than this.
