### ISSUE TITLE
does not update..

### ISSUE THREAD

**Issue by mclaudiopt** [bspranger/Xiaomi#139]
hi there
i sucessfully paired my xiaomi temperature and humidy sensor, it even got 1 reading of temp and humid (altough batt level is stated as 0)

after 1 hour i have no more reading. is there anyway to force readings?
how can i fix it? 
thanks

**Comment by kevindc1** [comment]
I have the same issue here. I ordered a Aqara temperature and Humidity sensor back in 2018 and the device handler i have for it v1.3 works perfect still to this day.  This past week i received me new Xiaomi Temperature and Humidity sensor.. it will only stay connected for an hour or so and then disconnect and never would show the battery level. 
 I imagine they look like the same product but has variations with it. 
Any ideas?

**Comment by veeceeoh** [comment]
@kevindc1 - I doubt it's a variation of the product. What you describe sounds like an issue with a ZigBee repeater device that your new Temp & Humidity sensor is connecting to.

Please have a look at this post on the SmartThings Community Forums:

https://community.smartthings.com/t/original-aqara-xiaomi-zigbee-sensors-contact-temp-motion-button-outlet-leak-etc/113253/1492
