### ISSUE TITLE
Variant of Xiaomi Temperature Humidity Sensor not supported?

### ISSUE THREAD

**Issue by ralfbergs** [bspranger/Xiaomi#141]
I installed the two custom device handlers "Xiaomi Aqara Temperature Humidity Sensor" and "Xiaomi Temperature Humidity Sensor" from this repo, but I still can't get my sensor detected as something other than "Thing" (I have a sensor that looks exactly like the circular "Xiaomi Temperature Humidity Sensor" on the frontpage of this repo).

Here's my "raw description" from the IDE:

`01 0104 5F01 01 05 0000 0003 0019 FFFF 0012 07 0000 0004 0003 0005 0019 FFFF 0012`

Unfortunately I don't understand enough of this to "fix" the device handler myself. Is the above sufficient for you to (try to) add support for this device? Is there anything I can do to help with that?

**Comment by ralfbergs** [comment]
Interesting... I manually changed the device type in the IDE to "Xiaomi Aqara Temperature Humidity Sensor" and restarting the (new) SmartThings app, I see proper(?) metrics in the app: humidity, temperature, battery.

So it seems the device handler is definitely compatible, just that there is an issue with the "fingerprint"(?) to automatically detect the device type...

**Comment by veeceeoh** [comment]
Thanks for the issue report!

Unfortunately, the fingerprint matching is an "inexact science" where Xiaomi and Aqara devices are concerned. 

The normal procedure for _any_ pairing any device that is assigned as a generic "Thing" in SmartThings is to manual change the device type, as you've done.

I see that your "raw description" line includes some values that can be added to another fingerprint line in the device handler code, so I will stick that in and announce an updated version on the SmartThings Community Forums very soon.
