### ISSUE TITLE
Can't automate thing based on humidity from Xiaomi Aqara Temperature Humidity Sensor

### ISSUE THREAD

**Issue by horuktaras** [bspranger/Xiaomi#152]
When I'm trying to create some automation Aqara Sensor give s me only battery value. Can I get humidity and temperature data somehow?

![photo_2020-05-13_11-14-46](https://user-images.githubusercontent.com/17567972/81794123-f4f70200-9512-11ea-8fa4-6fe02e521d4e.jpg)

**Comment by rengelen85** [comment]
I experience the same in the latest SmartThings app for Android (1.17.47-22), but in the app for iOS it is still working fine. So it seems to be a bug in this specific version of the app, not the device handler

**Comment by horuktaras** [comment]
Tried an old classic app. Works ok.
![image](https://user-images.githubusercontent.com/17567972/82416625-0300d180-9a83-11ea-8310-da04ebea1199.png)
