### ISSUE TITLE
Temperature and humidity sensor battery level

### ISSUE THREAD

**Issue by lukaszgatnicki** [bspranger/Xiaomi#164]
Hi,

Most funtcionality works great. I can see a temperature and humidity. But the battery level still shows 0 and there is a red dot on the tile with battery info.

![Screenshot_20210203-184226_SmartThings](https://user-images.githubusercontent.com/32697925/106787257-c6e0c180-664f-11eb-942d-8ccce93d537d.jpg)

My SmartThings version is 1.7.60.23

Thank you for your help

**Comment by lukaszgatnicki** [comment]
I did nothing and it started to work after few hours. Sorry for the confusion.

**Comment by CLARENNE-Q** [comment]
Same Issue here ! I'am waitting ;)
