### ISSUE TITLE
Swap Lastcheckin and lastevent (Motion/press/open etc) 

### ISSUE THREAD

**Issue by tmleafs** [bspranger/Xiaomi#36]
Doing so means the the recently tab will look complete (My OCD is kicking in) as we can add the heart beat icon

`            tileAttribute("device.lastCheckin", key: "SECONDARY_CONTROL") {
                attributeState("default", label:'Last Update: ${currentValue}',icon: "st.Health & Wellness.health9")
            }`

Example of DH will look like
![screenshot_20180121-111432 small](https://user-images.githubusercontent.com/8752233/35215743-295be1c6-ff5d-11e7-891e-5baffe52592b.jpg)

Current Recently Tab looks like
![screenshot_20180122-100442 small](https://user-images.githubusercontent.com/8752233/35215720-163d927e-ff5d-11e7-8c5a-8111effde56a.jpg)

What it will look like with the change
![screenshot_20180122-100452 small](https://user-images.githubusercontent.com/8752233/35215717-148cea2e-ff5d-11e7-8544-54ee91e4b667.jpg)

**Comment by veeceeoh** [comment]
Having the heartbeat in the Recently events tab is great, but my OCD prefers the "Last Opened" line in the open/close status tile, and not to drop AM / PM to a second line. :smile:

**Comment by alecm** [comment]
I love the heartbeat for a checkin in the recently field!   Agree that I'd prefer to keep Last Checking below and Last (Motion, Opened, etc.) in main tile.

**Comment by bspranger** [comment]
What are we going to do here?  Implement or close?

**Comment by tmleafs** [comment]
Well with the refresh button being removed with could play around see if we can get the heartbeat icon and the checkin to display in a nice way

**Comment by bspranger** [comment]
Let's clean up the refresh button then come back and revisit this one.  Agreed?

**Comment by tmleafs** [comment]
Battery checkin now removed from recently tab in #83
