### ISSUE TITLE
Both Temp/Humidity sensor DTHs not updating mobile app display??

### ISSUE THREAD

**Issue by veeceeoh** [bspranger/Xiaomi#45]
On the [[RELEASE] Xiaomi Sensors and Button (beta) thread](https://community.smartthings.com/t/release-xiaomi-sensors-and-button-beta/77576) on ST Community Forums, two users are reporting that when using bspranger/Xiaomi DTHs with their Temp/Humidity sensors, the ST mobile app does not display any values for anything, like this:

![temp-humid mobile app display](https://user-images.githubusercontent.com/33558908/35313025-1afe3342-0073-11e8-928b-f5726f57d6dd.PNG)

User @cowboysdude has "original" Xiaomi Temp/Humidity sensors, and user @busybeee is working with an Aqara Temp/Humidity sensor, and they are both reporting the same problem. So it seems there may be an issue with both Temp/Humidity sensor DTHs.

Both of them say they can see the temp / humidity reports in the "events" log (I'm not sure which log they are referring to - so I will ask). This tells me that their devices are paired okay, but for some reason the tiles are not being updated with the latest reported values.

It's really difficult to troubleshoot this for me because I don't have either of the Temp/Humidity sensors so I can't confirm the problem with the mobile app not displaying any values (like in the above screen shot.)

I would recommend reading through posts from the past two days in that thread to get a sense of what they're experiencing.

**Comment by veeceeoh** [comment]
So, looking through at least the Aqara Temp/Humidity DTH, I see a lot of code that checks whether the temp offset / pressure offset / pressure units have been set by the user could just be replaced by setting defaults for each in the `Preferences{}` section. 

I see that @tmleafs used defaults for his Min Volts / Max Volts preference settings, and it seems to work great.

So why not use defaults?

**Comment by veeceeoh** [comment]
Sorry I see now you already had a default for the Pressure units.

However, I also suggest following @tmleafs lead by adding `type: "decimal"` for the temp offset and pressure offset settings. That forces a numeric keypad (at least for iOS users) and only allows numeric values to be entered.

So the preferences section of the Aqara Temp/Humidity DTH would change to:

```
preferences {
        section {
            input title:"Temperature Offset", description:"This feature allows you to correct any temperature variations by selecting an offset. Ex: If your sensor consistently reports a temp that's 5 degrees too warm, you'd enter '-5'. If 3 degrees too cold, enter '+3'. Please note, any changes will take effect only on the NEXT temperature change.", displayDuringSetup: true, type:"paragraph", element:"paragraph"
            input "tempOffset", "number", title:"Degrees", description:"Adjust temperature by this many degrees", type: "decimal", range: "*..*", defaultValue: 0, displayDuringSetup: true, required: true
        }
        section {
            input name:"PressureUnits", type:"enum", title:"Pressure Units", options:["mbar", "kPa", "inHg", "mmHg"], description:"Sets the unit in which pressure will be reported", defaultValue:"mbar", displayDuringSetup: true, required: true
        }
        section {
            input title:"Pressure Offset", description:"This feature allows you to correct any pressure variations by selecting an offset. Ex: If your sensor consistently reports a pressure that's 5 too high, you'd enter '-5'. If 3 too low, enter '+3'. Please note, any changes will take effect only on the NEXT pressure change.", displayDuringSetup: true, type: "paragraph", element:"paragraph"
            input "pressOffset", "number", title:"Pressure", description:"Adjust pressure by this many units", type: "decimal", range: "*..*", defaultValue: 0, displayDuringSetup: true, required: true
        }
    }
```

But, what does `displayDuringSetup: true` and `required: true` do? I noticed in @tmleafs Min Volts / Max Volts preference settings code, `displayDuringSetup` isn't defined, and although it has `required: false`, it still works fine.

**Comment by tmleafs** [comment]
Well displayDuringSetup: true I believe should bring up the settings when you add the device but never seen it work, required means if they go to the device settings and if set to true they will have to enter something in the field if its empty. If defaultvalue is used required isnt needed as the field cant be blank

**Comment by bspranger** [comment]
I believe this can be closed as it was a problem of the time zone not being set.  There is another issue to fix the timezone.

**Comment by bspranger** [comment]
This was a time zone issue.  There is an open item to resolve the timezone.
