### ISSUE TITLE
DH version

### ISSUE THREAD

**Issue by bspranger** [bspranger/Xiaomi#46]
Not sure if we could pull it off but I am so tempted to try and place a version in the DH so when ppl submit an issue they can refer to the version of DH they are using and a screenshot would automatically capture the version..

**Comment by veeceeoh** [comment]
Can the version be date-based or date&time-based?

Such as 012318.0850

**Comment by bspranger** [comment]
I wonder if we can put tags in the github repository so that when we commit it embeds the revision into the DH.  That way it would automatically update and we would not need to remember to update the version.

**Comment by veeceeoh** [comment]
I have no idea, but that would be really cool!

**Comment by tmleafs** [comment]
Can only see it being a manual thing we have to do, Other DH's/Apps call a file in github for update notifications but doing so would add a huge amount of code

**Comment by bspranger** [comment]
Ok, as this is a "like to have" and a manual process, I say we shelve it.

**Comment by foz333** [comment]
We have (eg V 1.0 of humidité) this at start in commets, we could add again so it appears in preferences/settings at the end of the section... that way people have an access to this without having people go through the H(t)D and it won't interfere with the interface.... and we can close this issue.
Tbh I don't imagine the versions would  change too much anyway.
