### ISSUE TITLE
Hub timezone not set results in DTHs not working at all

### ISSUE THREAD

**Issue by veeceeoh** [bspranger/Xiaomi#47]
Just opening this as an official issue, even though we're all well aware of it.

It looks like one or maybe two users just today were at their wits' end with frustration over their ST mobile app not displaying their sensor's reported values correctly or not at all - and it turns out their hub's timezone wasn't set yet.

So there must be some way, as @bspranger has attempted to code, to check whether the timezone setting is null and if it is, use a default timezone to avoid all the null errors that make the device handler not work correctly.

**Comment by tmleafs** [comment]
Looking at other apps not seen anything in any DH's doing this 

> if(!location?.timeZone || !location?.zipCode) {
> log.debug("SmartThings Location not returning (TimeZone: ${location?.timeZone}) or (ZipCode: ${location?.zipCode}) Please edit these settings under the IDE")
> }

location.timeZone outputs this for me
> sun.util.calendar.ZoneInfo[id="Europe/London",offset=0,dstSavings=3600000,useDaylight=true,transitions=242,lastRule=java.util.SimpleTimeZone[id=Europe/London,offset=0,dstSavings=3600000,useDaylight=true,startYear=0,startMode=2,startMonth=2,startDay=-1,startDayOfWeek=1,startTime=3600000,startTimeMode=2,endMode=2,endMonth=9,endDay=-1,endDayOfWeek=1,endTime=3600000,endTimeMode=2]]

So a US ET user could output theirs and use that

**Comment by veeceeoh** [comment]
Okay, I think I found a way to do the location.TimeZone check without using that super long string.

From the [Sonos Music Modes SmartApp](https://github.com/SmartThingsCommunity/SmartThingsPublic/blob/master/smartapps/smartthings/sonos-music-modes.src/sonos-music-modes.groovy) in the SmartThingsPublic GitHub repository:

```
private getDaysOk() {
	def result = true
	if (days) {
		def df = new java.text.SimpleDateFormat("EEEE")
		if (location.timeZone) {
			df.setTimeZone(location.timeZone)
		}
		else {
			df.setTimeZone(TimeZone.getTimeZone("America/New_York"))
		}
		def day = df.format(new Date())
		result = days.contains(day)
	}
	log.trace "daysOk = $result"
	result
}
```

Actually, loads of SmartApps in SmartThingsPublic use the same function (or similar).

The key bit of code there overriding the timezone when it's not already set on the hub is `TimeZone.getTimeZone("America/New_York")`. I just don't quite understand how to integrate it into the Xiaomi DTHs.

**Comment by bspranger** [comment]
I would love to find a solution for this one.

It has been a real pita.

**Comment by tmleafs** [comment]
I have submitted a suggestion to the beta team that users that have not selected timezone or zip code should be force too in the next smartapp update

**Comment by tmleafs** [comment]
Got a reply from the beta team

> Steven, I agree with you and this causes us a lot of headaches as well.  I've added this request internally.  Thanks!

**Comment by veeceeoh** [comment]
While we're waiting for that fix to come from ST (which will probably take a while), do any of you know if there's a way to **un-set** the timezone in order to test code that overrides a null timezone setting with a default one?

**Comment by tmleafs** [comment]
My honest feeling coding round it isn't helping anyone in the long run like I what NST Manager and WebCore do which is what I posted above. Just fell there IDE and recently tab with warnings

> if(!location?.timeZone || !location?.zipCode) {
> log.error("SmartThings Location not returning (TimeZone: ${location?.timeZone}) or (ZipCode: ${location?.zipCode}) Please edit these settings under the IDE")
> sendEvent(name: "TimeZoneError", value: "You have a Time Zone problem, More Info in IDE Logs")
> }

put this code inside the following function
> def  parse(String description) 

and everytime something happens they get a warning in IDE and recently tab

**Comment by veeceeoh** [comment]
Hold the press! I figured it out!

Code is all ready, I just can't figure out this damn multiple commits into one pull request thing. :/

**Comment by veeceeoh** [comment]
Okay, Pull Request submitted.

**Comment by veeceeoh** [comment]
> My honest feeling coding round it isn't helping anyone in the long run like I what NST Manager and WebCore do which is what I posted above. Just fell there IDE and recently tab with warnings

@tmleafs - I agree fully, so I added an error message / event error message to alert the user to my solution. 

What I'd rather not see is, as a result of not having set their location, people getting completely frustrated with the Xiaomi DTHs thinking there's 1) something wrong with the DTHs, 2) something wrong with their sensors, or 3) they're doing something wrong. The workaround allows the functions of the DTH to work normally, but the date/time stamps won't match the user's local timezone (unless they live in GMT!) so it will hopefully prompt them to look at their log / events and will see the error messages.

**Comment by bspranger** [comment]
Merged
