### ISSUE TITLE
Minor UI Issue on Iphone - Temp (and Humidity) Offset + or -  - cant write +

### ISSUE THREAD

**Issue by alecm** [bspranger/Xiaomi#56]
I started testing the updated  version of the Temp/ Humidity sensors 
There's a small UI issue with both the temperature and the humidity offset preferences at least on iPhone. The keyboard that comes up has a little + and - at top and the numbers under it. All cool. But you can't actually type a +3 the plus key is inactive. You can, however, type a '-' sign. Unless someone knows a way to 'activate' the plus key - I suggest we change the instructions to say '3' or '-3' rather than '+3' or '-3'.

Plus does nothing - doesn't type a +
![img_3474 1](https://user-images.githubusercontent.com/3035095/35456961-418e161a-02a5-11e8-890b-a82ec6c69292.jpg)

Minus actually changes the value to a negative and put in '-' character
![img_3475 1](https://user-images.githubusercontent.com/3035095/35456966-45ff99d0-02a5-11e8-94c6-88c2518a8525.jpg)

**Comment by veeceeoh** [comment]
Agreed on this, as long as the Android UI is similar. 

Yesterday, I had put together code that included making this change as part of a cleanup of the preferences code and description, but now I'm waiting for the 2 open Pull Requests to get merged first.

**Comment by alecm** [comment]
Good point - can anyone comment on this in Android?  (I don't have any Android device, I'm afraid)

**Comment by veeceeoh** [comment]
By the way, all of the revised preferences text for any DTHs with an offset setting now don't mention using + for positive offsets.

Still don't know what Android users see when they edit any of these settings marked as `type: number` or `type: decimal`.

**Comment by alecm** [comment]
I think we can close this for now then.  This is pretty minor.
