### ISSUE TITLE
Can't save current version.  Extra } line 224

### ISSUE THREAD

**Issue by scoob8000** [bspranger/Xiaomi#58]
Tried updating this guy via the repo and get an error 500.   Manually pasting it in the ST IDE yields and error.     I got it to save by removing the extra close curly bracket on line 224.

I'm pretty new to github, not sure if an issue was the proper thing to do, but..   

https://github.com/bspranger/Xiaomi/blob/48848b7ba8557cbbf2a196256b70b1b2b495892e/devicetypes/bspranger/xiaomi-temperature-humidity-sensor.src/xiaomi-temperature-humidity-sensor.groovy#L224

**Comment by bspranger** [comment]
Please try updating from git.

**Comment by scoob8000** [comment]
Just updated and it's working now.
