### ISSUE TITLE
What's preferred way to update fork? 

### ISSUE THREAD

**Issue by alecm** [bspranger/Xiaomi#62]
This is a question to you more experienced Githubbers.  I'm currently only using the web version though ok w/ getting into the command line if absolutely necessary.   I just did a pull request to update a single line in one DTH and noticed that it was also "committing"  the pulls I did a couple of times to bring my fork up to date w/ Brian's. Does that matter?  It looks kind of messy. 

What's preferred process to keep things clean when I want to update my fork?   What I've read on the command-line stuff (rebasing and all) seems fairly tedious.    Should I just delete my fork and refork?  Does that cause other problems?

Thanks!

**Comment by tmleafs** [comment]
I just use the browser or commit from ST Ide. Yea your get that annoying commit if you do a pull to update your master. Put just check your pull request that it's only doing what you want to change and it and merge its fine.

**Comment by veeceeoh** [comment]
I am not experienced at all, but the pulls I've been doing to update my fork don't show up in any commits I make as long as I make the commits by edits to files in the bspranger/Xiaomi respository, and not to my fork of it.

**Comment by alecm** [comment]
Thanks @tmleafs and @veeceeoh - I'm not going to worry about it then as long as it only updates what's needed.

I'm going to close this - thanks for the feedback.

**Comment by alecm** [comment]
Got feedback - thnx!
