### ISSUE TITLE
Heads Up: Display Issues on iPhone app  - both custom and standard DTHs

### ISSUE THREAD

**Issue by alecm** [bspranger/Xiaomi#80]
You're all probably aware of it - per thread at https://community.smartthings.com/t/ios-2-14-0-released-1-30-18/117246/83 it looks like rendering is off on both standard and custom DTHs on iPhone 

Here's what our most up-to-date Xiaomi Aqara Motion Sensor is looking like on my iPhone this morning - note the weird icon before "Last Updated"  - how off the value tiles look - 

![image](https://user-images.githubusercontent.com/3035095/35769000-62e43dac-08d2-11e8-987d-1fe5ad8ecdbd.png)

This is what my Iris Motion Sensor - using **completely** standard DTH is looking like  - even worse!
![image](https://user-images.githubusercontent.com/3035095/35769016-a5622b30-08d2-11e8-93ed-a931d93ed3a7.png)

Suggest we hold off on any image "reconciliation"  between Android and iPhone until this gets straightened out...

**Comment by tmleafs** [comment]
The last phone app updates are shite. ST love pissing everyone off the last month or so

**Comment by veeceeoh** [comment]
This is a really weird one. I updated to the new 2.14.0 iOS ST app two days ago, and the rendering issue only just showed up last evening, right at the same time I was pairing my new Aqara Temp/Humidity Sensor, Motion Detector, and 2-button wall switch.

I noticed all kinds of things that need to be addressed with the DTHs, but I guess I should hold off until things are resolved with the rendering issues to make sure they aren't causing what I'm seeing.

Interestingly, there's [a post on the iOS 2.14.0 thread](https://community.smartthings.com/t/ios-2-14-0-released-1-30-18/117246/88?u=veeceeoh) claiming that downgrading to 2.13.0 returns the rendering to normal. But you have to be running iOS 11.x to get the downgrade option. Sadly, I'm still on iOS 10.x as I'm using apps that break with iOS 11, so I can't confirm the downgrade works as a fix.

**Comment by veeceeoh** [comment]
So I found a [post on ST Community forums](https://community.smartthings.com/t/ios-background-colors-labels-broken/117716?u=veeceeoh) that seems to explain how the iOS app UI rendering suddenly got messed up yesterday.

Apparently in their zeal to resolve a crash of one particular device handler that started happening with the iOS 2.14.0 update, an employee of ST (software engineer?) made a change to the way tile background colors are handled, yesterday afternoon (US West coast time), which resulted in a small shopping list of UI glitches for the entire ST iOS app v2.14.0 user base.

Unaware that it affected a large variety of device handlers and SmartApps, he said he'd get to fixing it next Monday.

Oops.

**Comment by alecm** [comment]
Correlation is not causation - but I woke up this morning to every single one of my Xiaomi devices offline - the couple of re-pairings I've done haven't stuck (e.g., started ok then never started reporting checkins) and then I was out all day) - hope things go better tomorrow - I think I'm going to have to actually do a remove and reconnect on all...  c'est la vie

**Comment by alecm** [comment]
Looks like they fixed the rendering issues this morning on iOS. Closing.
