### ISSUE TITLE
Button preferences update - comments?

### ISSUE THREAD

**Issue by alecm** [bspranger/Xiaomi#86]
Hello,

I've already done a pull on this (to @tmleafs) standardisation branch - hope I got it right.

1. On the old button - still had a 'how many seconds is held' preference - as far as I can tell that functionality has been deprecated for now.  I removed it until/unless we decide to reinstate it. 
Notice - if you had a previous version and had entered some 'held' value - it still shows down below as a "ghost"  in preferences.  If you click the little 'x' it disappears. 
(sorry - forgot to take screenshot before it went away) 

2. On both buttons,  was just seeing "Which?"  for the Momentary/Toggle preference.  Switched "description" to "title".   While I was in there I changed the language to simply "Momentary or toggle? "  and I switched the default to "Momentary".   I think for the first time user the way it works as a "momentary" push button is more intuitive.  Default "toggle"  has led me to think it's getting stuck until I realized it was on toggle.    Hope that's ok - please push back if you disagree.

**Comment by tmleafs** [comment]
Changes merged
