### ISSUE TITLE
Icons - Battery Android Vs. iphone

### ISSUE THREAD

**Issue by foz333** [bspranger/Xiaomi#92]
Weird or non display of icons from certain https and how they render differently on ios and android

**Comment by foz333** [comment]
instead of talking about in multiple places i thought one common ground best.
Obviously i'm aware this is a ST issue so resolution unlikely but hoping we can find a common method that works.

**Comment by foz333** [comment]
Banged my head a few times against the wall on this one today... 
icon:"https://dl.dropboxusercontent.com/s/m0l2oahnynrt2es/Battery-100.png"

*on android i cant get this file to load when i have in my repo so i used my DB

i'm happy wityh this on android... if anybody can validate on ios.
![screenshot_2018-02-13-16-38-47](https://user-images.githubusercontent.com/34963428/36158889-b6b21932-10dd-11e8-8923-9388fe0092fe.png)

**Comment by bspranger** [comment]
Looks nice!  Let's hope it works.

**Comment by foz333** [comment]
icon:"https://dl.dropboxusercontent.com/s/75khlzz1uwr8i39/whiteBattery.png"
icon:"https://dl.dropboxusercontent.com/s/j2yq67npzukgiqd/whiteHumidity.png"

couple little changes to fix size in recently screen. Hope somebody here can confirm these are ok in IOS, @tmleafs  or @veeceeoh either of you ios or access to a device?

![screenshot_2018-02-13-22-34-19](https://user-images.githubusercontent.com/34963428/36175055-850bde14-110e-11e8-832b-37e262d5dac8.png)
![screenshot_2018-02-13-22-34-26](https://user-images.githubusercontent.com/34963428/36175056-857feaac-110e-11e8-9107-32d433446118.png)

**Comment by veeceeoh** [comment]
@foz333 - Sorry to say, the battery icon doesn't work on iOS. All I see is grey type on a white background. This is because it's rendered much much larger on iOS, so I'm just seeing a white area in the middle of your icon file. Same thing for the droplet icon.

The only way it will work size / position-wise is to be quite small, above the center, but not too close to the top. So on iOS it appears smaller, but above the text, and on Android, larger, but not going off the top of the circle.

**Comment by veeceeoh** [comment]
![img_2212](https://user-images.githubusercontent.com/33558908/36180857-f285541c-10d6-11e8-9524-cfd4bb2939b0.PNG)

**Comment by alecm** [comment]
Dang - and they look so nice on android...   (I have iOS)
Wonder if there's a Samsung sabotage ?   (Conspiracy theory! - kidding)

**Comment by foz333** [comment]
I think i start to see the difference in rendering 

can @veeceeoh or another ios-er try this...

icon:"https://dl.dropboxusercontent.com/s/fubh7vdfgih01qf/Battery400.png"

**Comment by bspranger** [comment]
this looks sweet on Android.  Here to hoping it works on IOS.

**Comment by alecm** [comment]
Here it is on iOS  - at 100% and then at 91%

I'd say we have a winner!  Nice job, @foz333 !!!

![image](https://user-images.githubusercontent.com/3035095/36219269-cab3dce8-1184-11e8-82ac-79b15c1fc161.png)
![image](https://user-images.githubusercontent.com/3035095/36219314-f24371ba-1184-11e8-91e2-bc310d672a08.png)

**Comment by foz333** [comment]
Thanks @alecm that gives me something to work with. 
Here is android equivalent, I'll enlarge the image a little, try to position it a little lower and sharpen it. 
I'll upload the pad and png to @bspranger repo... but I'm pretty sure android ST app doesn't like https://. 

![screenshot_2018-02-14-19-25-26](https://user-images.githubusercontent.com/34963428/36224587-61b0a12e-11c8-11e8-92fa-908dccac9cf7.png)

**Comment by alecm** [comment]
As a note - when you add the icon in iOS - it looks good in the main app screen - you do lose display of the percentage in the "recently"  (which I think is normal).   It's nice to have the information - so we could just modify the 'recently' message as I did below to report both percent and raw value. 

- The 11:55 am report at bottom is before I added the icon - note white percentage value 
- The following reports up to 2:40 pm are after I added the icon
- The last report at 3:35 pm shows both percentage and raw value in the text  - so not having the percentage in the green circle doesn't matter as much  (yes, I know I'm missing a left parenthesis) 

Thoughts?   I think this should not hold up us finally getting an icon!

![image](https://user-images.githubusercontent.com/3035095/36227145-1c32f1a8-119e-11e8-930f-668683611a4f.png)

**Comment by veeceeoh** [comment]
I will miss having the percentage in the Recently tab, but adding the percentage to the event description works.

Now @foz333 - can you do the same (in white) for the droplet icon? If yes, then we have new icons for the temp/humidity sensors as well!

Also, where will the .png files be hosted? Shouldn't be on someone's personal dropbox account...

**Comment by foz333** [comment]
I agree, dropbox is horrible and limited i can's replace the file and keep the url, so every time i modify the image i change the url... complete pain in the balls.  

I'll make the final edit to battery and do the water image tomorrow.  Upload them and the psd to @bspranger git and see if we can use the git url.  Ive been using https://www.photopea.com/ its just like online photoshop with no registration... so work friendly.

**Comment by foz333** [comment]
@alecm ... jeez ios is fussy.

Android pretty much takes any icon size and just works, this applies to the recently tab too.

**Comment by veeceeoh** [comment]
@foz333 - So, I took your battery icon, sharpened it and moved it down a tiny bit, and also made a brand new icon for the humidity tile. I saved them in Photopea, as you've used, with the hopes that it display for everyone.

They're hosted on my GitHib, here:
https://raw.githubusercontent.com/veeceeoh/Xiaomi/master/images/Battery400r2.png
https://raw.githubusercontent.com/veeceeoh/Xiaomi/master/images/Droplets400.png

If they don't display, maybe they need to be hosted elsewhere as you've theorized.

Here's how they look for me:

![img_2213](https://user-images.githubusercontent.com/33558908/36236115-2b11c4be-11a9-11e8-892d-c32d36b663fe.PNG)

A bit off topic, but I'd like to change the Pressure tile from valueTile to standardTile which I think will make the numbers bigger (on iOS anyhow, will need to check the effect on Android).

**Comment by alecm** [comment]
As the humidity guy - which probably sounds weird - I'm sooo loving that icon!!!!!   Honestly SmartThings should be paying attention to these DTHs!

**Comment by foz333** [comment]
For me this is a win. 
Icons from the @veeceeoh github repo both look the part on my Android devices, even in activity feed :-p
ps. also like the new humidity icon.

![screenshot_2018-02-15-10-28-11](https://user-images.githubusercontent.com/34963428/36249554-5df37dc2-123b-11e8-9a3a-bdc0bfeac699.png)

![screenshot_2018-02-15-10-47-19](https://user-images.githubusercontent.com/34963428/36250508-4e05d95c-123e-11e8-98f6-9c451bfa2a50.png)

Awaiting more feedback, but if size is good for others i vote close.

**Comment by foz333** [comment]
the battery icon in activity feed at the bottom is an old one, the new version displays in the same location as the humidity icon near at top of list... all i'm trying to say is dont change a thing... please.

**Comment by foz333** [comment]
in the uk atmospheric or barometric pressure is usual obsreved on a dial, like a clock face.... rather than a huricane. like this https://raw.githubusercontent.com/foz333/Xiaomi/master/images/atmoPressure.png

Nnow that i think about it, i know space is the problem but should unit not be displayed for the pressure...  then again easier not to.

I think this looks a little more pro than the hurricane icon:

![screenshot_2018-02-15-11-33-37](https://user-images.githubusercontent.com/34963428/36252318-7f4f4402-1244-11e8-8476-458122e4e341.png)

**Comment by alecm** [comment]
Love the pressure dial - totally agree.  Like looking at a barometer...

**Comment by chnsawalex** [comment]
Good idea getting rid of the hurricane and nice work on the dial. The dial idea could work if it's made to look more like the other icons, as in part of the same theme. Can it be simplified a bit and lines made thicker?

Also I searched Google photos to get ideas for how others represent barometric pressure. I like something like this (https://goo.gl/images/Lm1xUf). There is no mistaking what you're trying to say with that icon. Any thoughts?

**Comment by veeceeoh** [comment]
What do you guys think of this:

![img_2219](https://user-images.githubusercontent.com/33558908/36288294-ce3dc1e0-126e-11e8-96a6-9e6f4586d1a7.PNG)


In order to display it this way on iOS, I have to use this code:

`        valueTile("pressure", "device.pressure", inactiveLabel: false, width: 2, height: 2) {
            state "pressure", label:'${currentValue}', icon:"https://raw.githubusercontent.com/veeceeoh/Xiaomi/master/images/atmoPressureV4.png", backgroundColor: "#999999
`

So that changes `standardTile` to `valueTile`, and removes `decoration:"flat"`. The png file is not transparent so that I could use a square with rounded corners (the pressure value was too big for a circle.

I really hope it also looks good on Android!! Let me know.

**Comment by foz333** [comment]
I'm on phone... but I'll try and test this now. Back in 10 (hopefully).
BTW I really like the look in your SS.

**Comment by foz333** [comment]
Android does not like that...  or my phone didn't copy paste well. Both are equally possible.

![screenshot_2018-02-17-13-51-35](https://user-images.githubusercontent.com/34963428/36341133-dc4e03d6-13e9-11e8-8fe5-2f089544e2ed.png)

**Comment by veeceeoh** [comment]
Oh well, but I'm not finished yet. :grin:

**Test 2**: Try removing the `backgroundColor` from the code above, so it's this:
```
        valueTile("pressure", "device.pressure", inactiveLabel: false, width: 2, height: 2) {
            state "pressure", label:'${currentValue}', icon:"https://raw.githubusercontent.com/veeceeoh/Xiaomi/master/images/atmoPressureV4.png"
        }
```
That gives me this for the tile:
![test2](https://user-images.githubusercontent.com/33558908/36344065-9ad40d12-13c9-11e8-8b87-2fa01a2c9f3d.png)
(not as nice with the grey numbers, but it would be great if it works, and the background can be made a bit darker for better contrast)

**Test 3**:  Same as Test 2, but use a different icon file with grey graphic and transparent background:
```
        valueTile("pressure", "device.pressure", inactiveLabel: false, width: 2, height: 2) {
            state "pressure", label:'${currentValue}', icon:"https://raw.githubusercontent.com/veeceeoh/Xiaomi/master/images/atmoPressureV5.png"
        }
```

Test 3 gives me this:
![test 3](https://user-images.githubusercontent.com/33558908/36344379-5dabda00-13ce-11e8-9514-e4c6f5e702e7.PNG)

Otherwise, go back to `standardTile` with the V5 pressure icon, but then the number is still so small on iOS.

If we all agree on a new pressure icon, I'd like to suggest rearranging the order of those three tiles on the Aqara T/H sensor DTH as I've done. I think it looks better with the non-circle tile in the center.

**Comment by foz333** [comment]
I like the SS above... this is how I set up my screen after my previous post. Since this affects all DHS maybe we can add in issues 97 on same pull, kill 2 birds with one stone

**Comment by veeceeoh** [comment]
So, @foz333 - did Test 2 or Test 3 work for you on Android?

By the way, I edited the barometric pressure dial image to make the lines thicker, and look more similar to the style of the other two icons.

**Comment by foz333** [comment]
@veeceeoh ... Test 2 and 3 respectively. 

![screenshot_2018-02-18-09-23-54](https://user-images.githubusercontent.com/34963428/36349867-cb0877c4-148d-11e8-94a5-109a4cf3bdd4.png)
![screenshot_2018-02-18-09-25-08](https://user-images.githubusercontent.com/34963428/36349868-d27047b2-148d-11e8-885f-2df50dc4f9c8.png)

**Comment by alecm** [comment]
Comment on test 2 - maybe avoid this one because with the square it looks just like a bathroom weight scale -  might be confusing. Love the other one and also all the work that y'all are doing to overcome the rendering limitations across platforms.

**Comment by veeceeoh** [comment]
Okay, so I went back to your original pressure icon, and thickened the lines. If the code is returned to the way it was before, with the link to my modified icon:

```
        standardTile("pressure", "device.pressure", inactiveLabel: false, width: 2, height: 2) {
            state "pressure", label:'${currentValue}', icon:"https://raw.githubusercontent.com/veeceeoh/Xiaomi/master/images/atmoPressureV6.png"
        }
```

Then it should look good for everyone, Android / iOS, just the iOS text is quite small:

![img_2239](https://user-images.githubusercontent.com/33558908/36393315-e4d7f748-1563-11e8-91d0-1b88ddc4f3c4.PNG)

Maybe try one more time with this newest icon version, and `valueTile` in Android, to double check?

**Comment by foz333** [comment]
Android is okay with this... but your IOS test does look very little.

![screenshot_2018-02-19-22-25-09](https://user-images.githubusercontent.com/34963428/36397698-1a707ad2-15c4-11e8-8796-28de8f81e88b.png)

**Comment by veeceeoh** [comment]
@foz333 or anyone else with an Android device -  since I re-did the pressure logo, could we just try seeing how it looks with `valueTile` (which gets the much easier to read bigger text on iOS)??

```
        valueTile("pressure", "device.pressure", inactiveLabel: false, width: 2, height: 2) {
            state "pressure", label:'${currentValue}', icon:"https://raw.githubusercontent.com/veeceeoh/Xiaomi/master/images/atmoPressureV6.png"
        }
```

That can be the last test, and then a update can be released for all DTHs with the new battery icon, and the other icon(s) for the two Temp/Humidity sensor DTHs.

**Comment by foz333** [comment]
Android pretty consistent. Looks more or less the same.
I'm happy if you update battery for all.
Will you create a new folder in bspranger with icons or keep in current location?
For homogène maybe best to keep all in his git.

The smoke detector can be pulled before icon modification too.

![screenshot_2018-02-22-08-02-19](https://user-images.githubusercontent.com/34963428/36524628-ecbeac82-17a6-11e8-8fa2-9da24060932f.png)

**Comment by veeceeoh** [comment]
I have already uploaded the new icons to bspranger/Xiaomi/images. :smile:

I will create a new pull for the icon update, so we can all check one last time.

**Comment by veeceeoh** [comment]
Pull #101 created!

I think we can close this Issue, right??
