### ISSUE TITLE
Reference to community page

### ISSUE THREAD

**Issue by foz333** [bspranger/Xiaomi#97]
I think it would be a good idea to add a link in the comments at top of all the DHs to the reference the Community thread + Git Source (not everybody has the linked code).

Next time Samsung do a major update and break everything it may help people get to the right place quicker.

Im assuming that an actual clickable link in the preference is not possible (I've not checked).

**Comment by veeceeoh** [comment]
A clickable link isn't possible, but - Sure, sounds good.
