### ISSUE TITLE
Fire Detector won't trigger Smart Home Monitor

### ISSUE THREAD

**Issue by emilakered** [bspranger/Xiaomi#98]
I tried out the Fire Detector today (thanks for the DTH!), and I discovered something strange. It works perfectly and triggers "SMOKE" on the device status page, but it doesn't seems to trigger Smart Home Monitor. I have the alarm set up for smoke detection (obviously), but neither the app nor any of the triggers reacted.

When I changed to the old beta DTH (https://github.com/inpier/inpier-devicetypes/blob/master/devicetypes/kennethevers/xiaomi-honeywell-smoke-detector.src/xiaomi-honeywell-smoke-detector.groovy), SHM worked as intended and triggered both warning in the app and my actions.

I don't know if SHM needs a special trigger in the code?

**Comment by foz333** [comment]
@emilakered I hadn't added mine to the SHM so thanks for the headsup.
I'll check try to check this out tomorrow.

**Comment by foz333** [comment]
Same issue on leak sensor too. I'll look at both this afternoon and try to check when I get back from work.

**Comment by emilakered** [comment]
@foz333 Hm, the leak sensor actually worked fine last time I tested it (late January). I'll give it another try as soon as I can!

(The screenshot also shows yesterdays successful fire alarm trigger (Brandlarm in Swedish) with the old DTH.)
![screenshot_20180219-101226](https://user-images.githubusercontent.com/31852416/36369959-7c52aeda-155d-11e8-97e6-b8608cfe07ce.png)

**Comment by veeceeoh** [comment]
@foz333 - I had a look at your DTH, and the event messages that get sent are totally different from what's sent with the older DTH:

The older DTH uses this createEvent() mapping:
`name: 'smoke'`
`value: 'detected'` or '`clear'`

and your DTH uses:
`name: 'fire'`
`value: 'smoke'` or `'clear'`

So, I suspect that may be the reason SHM isn't seeing the smoke detected event. I would also suggest going into SHM configuration and turning _off_ the "Use every Smoke detector" setting to check if the Xiaomi Honeywell sensor is seen by SHM as available.

**Comment by emilakered** [comment]
I can confirm it does. This is with the current DTH in the main branch here. It is selectable and configurable, but doesn't trigger SHM. :)

![screenshot_20180219-193230](https://user-images.githubusercontent.com/31852416/36392494-c67a0c30-15ab-11e8-8f33-29e46e42b049.png)

**Comment by foz333** [comment]
TBH I didn't really look at the original DH. I used the leak as the template and just went from there. I should have double checked with an official supported DH for correct terms to pass. I'll see if the value 'detected' plays better with the SHM.

**Comment by veeceeoh** [comment]
I just looked that the Fibaro Smoke Sensor DTH on the SmartThings Public repository, and I see this line:

`capability "Smoke Detector" //attributes: smoke ("detected","clear","tested")`

So yes, it needs to be `name: smoke`, and the three values as listed above.

**Comment by foz333** [comment]
@emilakered i've done a pull as per Fibaro above, can you check if this is any better for you with the SHM?
@veeceeoh if you can check the code changes, i think i got everything.

**Comment by emilakered** [comment]
@foz333 Great! Sure, I'll try it as soon as I can! It's very late here now though, so for obvious reasons setting of the fire alarm is a bad idea. Tomorrow!

**Comment by foz333** [comment]
no worries, think we are in same timezone, i can't even test in garage without fear of the little peoples ears being stimulated by this noisy thing.  I have no fears about hearing this in a real emergency thats for sure.

**Comment by emilakered** [comment]
Manages to test both the fire alarm and the leak sensor this morning. Working well, and triggering SHM as expected. Nice job! :)

![screenshot_20180221-083201](https://user-images.githubusercontent.com/31852416/36468025-eb301e48-16e1-11e8-8564-3064742fc87f.png)

**Comment by foz333** [comment]
Issue can be closed. I've also tested and working here too.
