### ISSUE TITLE
Minor issue - Xiaomi original temp humidity reporting unformatted lastCheckinDate

### ISSUE THREAD

**Issue by alecm** [bspranger/Xiaomi#99]
Hello, 

If you take a look at reports from the current Xiaomi original temp humidity you're getting

![image](https://user-images.githubusercontent.com/3035095/36354414-f3aa5972-14a1-11e8-8aaf-7ca22caf8396.png)

If I'm correct - "lastCheckinDate" doesn't need to be there anymore.   

Is that right ? 

Alec

**Comment by veeceeoh** [comment]
It's still used, just to update the "Last report" tile. It's set to `display: false` which just means it won't show up in the "Recently" tab when viewing the device in the ST mobile app, and also won't show up in IDE when viewing the "Displayed" event list for a device:

<img width="500" alt="screen shot 2018-02-19 at 10 05 12 am" src="https://user-images.githubusercontent.com/33558908/36391699-7969b46c-155c-11e8-859e-9dac5ce0a121.png">

If you change to view "all" or "from device" then you _will_ see the lastCheckin / lastCheckinDate listed. That's normal, nothing to worry about. I double-checked the code, and it's correct.

**Comment by veeceeoh** [comment]
Oh, sorry - just re-read your question. The `lastCheckinDate` is for WebCoRE users to make use of, if I understood correctly, because it wants the date in that raw format. I don't use WebCoRE (yet), so I didn't want to take it out.

**Comment by alecm** [comment]
ahhhh.... that explains it - a bit webcoreish compatibility (I know, I'm doing Stringify myself - will get to WebCoRE eventually) 

meanwhile - I'm closing - thanks for checking on it, Keith @veeceeoh
